name: SCCI Start
on: [push]
jobs:
  start-scci:
    runs-on: ubuntu-latest
    steps:
      - name: start-scci
        uses: cloudvaio/workflow-forge-trigger@main
        env:
          FORGE_TRIGGER: https://cloudva.io/trigger/22a639a68686143d526ee81f1e92bde4b7ec059b/pull
          FORGE_SECRET:  97fc31ba6b9407c8565fc5463124d862082a8cce
